# Generated by Django 3.2.5 on 2021-08-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('aId', models.AutoField(primary_key=True, serialize=False)),
                ('accNum', models.IntegerField(unique=True)),
                ('password', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('ownerId', models.CharField(max_length=20)),
                ('ownerName', models.CharField(max_length=50)),
                ('title', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TranInfo',
            fields=[
                ('tId', models.AutoField(primary_key=True, serialize=False)),
                ('send_accNum', models.CharField(max_length=20)),
                ('send_name', models.CharField(max_length=20)),
                ('receive_accNum', models.CharField(max_length=20)),
                ('receive_name', models.CharField(max_length=20)),
                ('money', models.IntegerField()),
                ('trade_date', models.CharField(max_length=20)),
                ('trade_time', models.CharField(max_length=20)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
                ('userName', models.CharField(max_length=50)),
                ('accCnt', models.IntegerField()),
                ('cash', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=50)),
            ],
        ),
    ]
