# Generated by Django 3.2.5 on 2021-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('aId', models.AutoField(primary_key=True, serialize=False)),
                ('aName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('contents', models.TextField(null=True)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
    ]
