# Generated by Django 3.2.5 on 2021-08-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cId', models.AutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=100)),
                ('contents', models.TextField(null=True)),
                ('img', models.CharField(max_length=20)),
            ],
        ),
    ]
